-- nvim --headless -u init.lua -i NONE -l tests/git/footer_search_installed.lua
local directory = vim.fn.tempname()
vim.fn.mkdir(directory, 'p')
local function git(args)
  local command = { 'git', '-C', directory }
  vim.list_extend(command, args)
  local result = vim.system(command, { text = true }):wait(5000)
  assert(result.code == 0, result.stderr)
end
local function input(keys)
  vim.api.nvim_feedkeys(vim.keycode(keys), 'xt', false)
  vim.api.nvim_exec_autocmds('CursorMoved', {})
  vim.wait(150)
end
local function check()
  git({ 'init', '-q' })
  for index = 1, 2 do
    vim.fn.writefile({ 'return ' .. index }, directory .. '/needle.txt')
    git({ 'add', '.' })
    git({ '-c', 'user.name=Test', '-c', 'user.email=test@example.invalid',
      '-c', 'commit.gpgsign=false', '-c', 'core.hooksPath=/dev/null',
      'commit', '-qm', 'Fixture ' .. index })
  end
  vim.api.nvim_set_current_dir(directory)
  vim.cmd.edit(directory .. '/needle.txt')
  input(' dr')
  assert(vim.wait(5000, function()
    local view = require('diffview.lib').get_current_view()
    return view and require('config.git.lifecycle').is_ready(view)
      and #view.panel.entries == 2 and view.panel.entries[2].git_details_loaded
  end, 10), 'History did not load')
  local view = require('diffview.lib').get_current_view()
  local panel = view.panel
  vim.api.nvim_set_current_win(panel.winid)
  for _, entry in ipairs(panel.entries) do
    panel:set_entry_fold(entry, false)
  end
  panel:highlight_item(panel.entries[1])
  input('/needle<CR>')
  assert(panel:get_item_at_cursor() == panel.entries[1].files[1], 'Collapsed filename not found')
  assert(not panel.entries[1].folded, 'Matching commit did not expand')
  assert(not view.git_diff_opened, 'Search opened a diff')
  input('n')
  assert(panel:get_item_at_cursor() == panel.entries[2].files[1], 'n did not find next commit file')
  assert(panel.entries[1].folded, 'Previous search expansion stayed open')
  assert(not panel.entries[2].folded, 'Next search match did not expand')
  input('N')
  assert(panel:get_item_at_cursor() == panel.entries[1].files[1], 'N did not find previous commit file')
  assert(panel.entries[2].folded, 'Reverse search left the previous match expanded')
  input('/Fixture 1<Esc>')
  assert(panel:get_item_at_cursor() == panel.entries[1].files[1], 'Cancel did not restore file match')
  assert(not panel.entries[1].folded and panel.entries[2].folded,
    'Cancel did not restore the previous temporary expansion')
  input('/Fixture 1<CR>')
  assert(panel:get_item_at_cursor() == panel.entries[2], 'Commit metadata search failed')
  assert(panel.entries[1].folded, 'Commit metadata match left previous match expanded')
  local origin = panel:get_item_at_cursor()
  input('/needle<Esc>')
  assert(panel:get_item_at_cursor() == origin, 'Cancelled search moved cursor')
  assert(panel.entries[1].folded and not panel.entries[2].folded,
    'Cancelled preview left a temporary expansion behind')
  panel:set_entry_fold(panel.entries[1], true)
  input('/needle<CR>')
  input('n')
  assert(not panel.entries[1].folded, 'Search collapsed a commit that was already open')
  assert(panel.entries[2].folded, 'Search left the previous temporary expansion open')
  input('n')
  assert(not panel.entries[1].folded and not panel.entries[2].folded,
    'Search did not distinguish existing and temporary expansions')
  input('/Fixture 1<CR>')
  local commit_cursor = vim.api.nvim_win_get_cursor(panel.winid)
  input('l')
  assert(vim.api.nvim_win_get_cursor(panel.winid)[2] > commit_cursor[2], 'l did not move right')
  input('h')
  assert(vim.deep_equal(vim.api.nvim_win_get_cursor(panel.winid), commit_cursor), 'h did not move left')
  assert(not panel.entries[2].folded and not view.git_diff_opened, 'Horizontal motion changed the commit')
  input('j')
  assert(panel:get_item_at_cursor() == panel.entries[2].files[1], 'j did not move onto child row')
  input('k')
  assert(panel:get_item_at_cursor() == panel.entries[2], 'k did not move onto commit row')
  input('o')
  assert(panel.entries[2].folded, 'o did not collapse commit')
  input('o')
  assert(not panel.entries[2].folded and not view.git_diff_opened, 'o did not expand without opening a diff')
  input('j')
  input('o')
  assert(vim.wait(3000, function()
    return view.git_diff_opened and require('config.git.lifecycle').is_ready(view)
  end, 10), 'o did not open the selected file')
  input('<C-q>')
  assert(not require('diffview.lib').get_current_view(), 'History did not close')
end
local ok, err = xpcall(check, debug.traceback)
vim.fn.delete(directory, 'rf')
if not ok then
  io.stderr:write(err .. '\n')
  vim.cmd('cquit 1')
end
print('Installed Git footer search tests passed')
vim.cmd('qa!')
