Source "common.tape"
Hide
Type `bash "$BECKNVIM_DEMO_ROOT/examples/nvim.sh" mooncake-transfer-engine/include/transfer_engine.h +70`
Enter
Sleep 5s
Type " h"
Sleep 2s
Show
Sleep 2s
# Browse projects and recent files using dashboard controls.
Type "l"
Sleep 1s
Type "j"
Sleep 1s
Type "h"
Sleep 1s
Type ":Theme"
Enter
Sleep 700ms
Type "paper"
Sleep 2s
Enter
Sleep 2s
Type ":Theme"
Enter
Sleep 700ms
Type "tokyo"
Sleep 2s
Enter
Sleep 2s
Type "j"
Enter
Sleep 2s
Type " h"
Sleep 1500ms
Hide
Type ":qa!"
Enter
